FAQexchange/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from profiles.views import ProfileFollowToggle, ProfileViewToggleQuestion, ProfileViewToggleFeedback, ProfileAjaxUpdateView, RegisterView, activate_user_view
from topics.views import TopicFollowToggle, TopicViewToggle, TopicAjaxCreateView
from questions.views import QuestionFollowToggle, QuestionFollowToggleFeedback, QuestionAjaxCreateView, QuestionAjaxUpdateView, QuestionAjaxDeleteView
from feedback.views import AnswerAjaxCreateView, AnswerFollowToggle, ReplyAnswerFollowToggle, AnswerAjaxUpdateView, AnswerAjaxDeleteView, CommentAjaxCreateView, CommentFollowToggle, CommentAjaxUpdateView, CommentAjaxDeleteView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='followProfile'),
    url(r'^profile-view-question/$', ProfileViewToggleQuestion.as_view(), name='viewProfileQuestion'),
    url(r'^profile-view-feedback/$', ProfileViewToggleFeedback.as_view(), name='viewProfileFeedback'),
    url(r'^topic-follow/$', TopicFollowToggle.as_view(), name='followTopic'),
    url(r'^topic-view/$', TopicViewToggle.as_view(), name='viewTopic'),
    url(r'^topic-create/$', TopicAjaxCreateView.as_view(), name='topicCreate'),
    url(r'^question-follow/$', QuestionFollowToggle.as_view(), name='followQuestion'),
    url(r'^question-follow-feedback/$', QuestionFollowToggleFeedback.as_view(), name='followQuestionFeedback'),
    url(r'^question-create/$', QuestionAjaxCreateView.as_view(), name='questionCreate'),
    url(r'^profile-update/(?P<pk>\d+)/$', ProfileAjaxUpdateView.as_view(), name='profileUpdate'),
    url(r'^(?P<pk>[\w-]+)/question-edit/$', QuestionAjaxUpdateView.as_view(), name='questionEdit'),
    url(r'^(?P<pk>[\w-]+)/question-delete/$', QuestionAjaxDeleteView.as_view(), name='questionDelete'),
    url(r'^(?P<slug>[\w-]+)/answer-create/$', AnswerAjaxCreateView.as_view(), name='answerCreate'),
    url(r'^(?P<pk>[\w-]+)/answer-edit/$', AnswerAjaxUpdateView.as_view(), name='answerEdit'),
    url(r'^(?P<pk>[\w-]+)/answer-delete/$', AnswerAjaxDeleteView.as_view(), name='answerDelete'),
    url(r'^answer-follow/$', AnswerFollowToggle.as_view(), name='followAnswer'),
    url(r'^reply-answer-follow/$', ReplyAnswerFollowToggle.as_view(), name='followReplyAnswer'),
    url(r'^(?P<pk>[\w-]+)/comment-create/$', CommentAjaxCreateView.as_view(), name='commentCreate'),
    url(r'^(?P<pk>[\w-]+)/comment-edit/$', CommentAjaxUpdateView.as_view(), name='commentEdit'),
    url(r'^(?P<pk>[\w-]+)/comment-delete/$', CommentAjaxDeleteView.as_view(), name='commentDelete'),
    url(r'^comment-follow/$', CommentFollowToggle.as_view(), name='followComment'),
    url(r'^user/', include('profiles.urls', namespace='profiles')),
    url(r'^topic/', include('topics.urls', namespace='topics')),
    url(r'^question/', include('questions.urls', namespace='questions')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
]

topics/urls.py
from django.conf.urls import url

from .views import TopicCreateView  # TopicDetailView  #

urlpatterns = [
    # url(r'^(?P<username>[\w-]+)/$', TopicDetailView.as_view(), name='detail'),
    url(r'^$', TopicCreateView.as_view(), name='create'),
]
#

templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<!-- user css -->
<style>
.grid-container {
  display: grid;
  grid-template-columns: auto auto auto auto auto;
  background-color: #FFFFFF;
  padding: 10px;
}
.grid-item {
  background-color: rgba(255, 255, 255, 0.8);
  border: 1px solid rgba(0, 0, 0, 0.8);
  padding: 5px;
  font-size: 14px;
  text-align: center;
}
</style>

templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>{{ button_name }}</button>
</form>

templates/snippets/js.html
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


templates/snippets/nav.html
 <div class='row text-center'>
    <h1>{{ request.user }}</h1> 
    <div class='grid-container' style='grid-template-columns: auto auto auto auto'>
        {% if request.user.is_authenticated %}
        <div class='grid-item' style="border: 2px solid rgba(255, 0, 0, 1)">
            <a href='{% url "topics:create" %}?q='>Topics</a>
        </div>
        <div class='grid-item' style="border: 2px solid rgba(0, 0, 255, 1)">
            <a href='{% url "questions:create" %}?q='>Questions</a>
        </div>
        <div class='grid-item' style="border: 2px solid rgba(0, 255, 0, 1)">
            <a href='{% url "profiles:detail" %}?q='>Users</a>
        </div>
        <div class='grid-item' style="border: 2px solid rgba(0, 0, 0, 1)">
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% else %}
        <div class='grid-item' style="border: 2px solid rgba(0, 0, 0, 1)">
            <a>Login</a>
        </div>
        {% endif %}
    </div>
</div>

templates/snippets/search-bar.html
<div class='row text-center'>
<form class='form' method='GET' action='.'>
<input type='text' placeholder="Search.." name='q' value='{{ request.GET.q }}'>
<button class='btn btn-default' type='submit'>Search</button>
</form>
</div>